experiment_name: 10000_l-town_
fixed_params:
  network: l-town.inp
  options:
    time:
      duration: 0
number_of_runs: 10000
result_processor:
  filter:
    filter_large_headlosses:
      max_value: 15
    filter_parallel_edges: null
  input_variables:
    link:
      properties:
      - initial_status
      - link_type
      - start_node_name
      - end_node_name
      signals:
      - flowrate
      - roughness
      - length
      - diameter
    node:
      properties:
      - node_type
      - elevation
      signals:
      - demand
      - head
  post_transforms:
  - node_names_to_ids
  target_variables:
    node:
      signals:
      - head
sampled_params:
  link:
    diameter:
      keys: all
      sampler:
        args:
        - 1
        - 1.5
        type: UniformScaler
    length:
      keys: all
      sampler:
        args:
        - 1.2
        - 0.9
        type: UniformScaler
    roughness:
      keys: all
      sampler:
        args:
        - 60
        - 160
        type: UniformSampler
  node:
    base_demand:
      keys: all
      sampler:
        args:
        - 0.0
        - 0.002
        type: UniformSampler
    base_head:
      keys: all
      sampler:
        args:
        - 1.2
        - 1.5
        type: UniformScaler
