experiment_name: 3000_mod_
fixed_params:
  network: mod.inp
  options:
    hydraulic:
      demand_model: PDD
    time:
      duration: 0
number_of_runs: 3000
post_transforms:
- node_names_to_ids
result_processor:
  filter:
    filter_large_headlosses:
      max_value: 20
  input_variables:
    link:
      properties:
      - initial_status
      - link_type
      - start_node_name
      - end_node_name
      signals:
      - roughness
      - flowrate
      - length
      - diameter
    node:
      properties:
      - node_type
      - elevation
      signals:
      - demand
      - head
  target_variables:
    node:
      signals:
      - head
sampled_params:
  link:
    diameter:
      keys: all
      sampler:
        args:
        - 0.8
        - 1.2
        type: UniformScaler
    length:
      keys: all
      sampler:
        args:
        - 0.8
        - 1.2
        type: UniformScaler
    roughness:
      keys: all
      sampler:
        args:
        - 0.8
        - 1.2
        type: UniformScaler
  node:
    base_demand:
      keys: all
      sampler:
        args:
        - 0.0
        - 0.003
        type: UniformSampler
    base_head:
      keys: all
      sampler:
        args:
        - 1.3
        - 1.5
        type: UniformScaler
